/*
 * Copyright The tarpm Project Authors
 * SPDX-License-Identifier: Apache-2.0
 */

#include <rpm/rpmtag.h>

#include "tarpm.h"

/*
 * Convert tag type to symbolic type name.  Caller must not free the
 * string returned.
 */
const char *
tag_type(rpmTagType type)
{
    switch (type) {
        case RPM_NULL_TYPE:
            return "(null)";
        case RPM_CHAR_TYPE:
            return "char";
        case RPM_INT8_TYPE:
            return "int8";
        case RPM_INT16_TYPE:
            return "int16";
        case RPM_INT32_TYPE:
            return "int32";
        case RPM_INT64_TYPE:
            return "int64";
        case RPM_STRING_TYPE:
            return "string";
        case RPM_BIN_TYPE:
            return "binary blob";
        case RPM_STRING_ARRAY_TYPE:
            return "string array";
        case RPM_I18NSTRING_TYPE:
            return "i18n string";
        default:
            return "(unknown)";
    }
}

/*
 * Convert tag value to symbolic tag name (matches RPM headers).
 * Caller must not free string returned.
 */
const char *
signature_tag_name(rpmSigTag tag)
{
    switch (tag) {
        case RPMSIGTAG_SIZE:
            return "RPMSIGTAG_SIZE";
        case RPMSIGTAG_LEMD5_1:
            return "RPMSIGTAG_LEMD5_1";
        case RPMSIGTAG_PGP:
            return "RPMSIGTAG_PGP";
        case RPMSIGTAG_LEMD5_2:
            return "RPMSIGTAG_LEMD5_2";
        case RPMSIGTAG_MD5:
            return "RPMSIGTAG_MD5";
        case RPMSIGTAG_GPG:
            return "RPMSIGTAG_GPG";
        case RPMSIGTAG_PGP5:
            return "RPMSIGTAG_PGP5";
        case RPMSIGTAG_PAYLOADSIZE:
            return "RPMSIGTAG_PAYLOADSIZE";
        case RPMSIGTAG_RESERVEDSPACE:
            return "RPMSIGTAG_RESERVEDSPACE";
        case RPMSIGTAG_BADSHA1_1:
            return "RPMSIGTAG_BADSHA1_1";
        case RPMSIGTAG_BADSHA1_2:
            return "RPMSIGTAG_BADSHA1_2";
        case RPMSIGTAG_DSA:
            return "RPMSIGTAG_DSA";
        case RPMSIGTAG_RSA:
            return "RPMSIGTAG_RSA";
        case RPMSIGTAG_SHA1:
            return "RPMSIGTAG_SHA1";
        case RPMSIGTAG_LONGSIZE:
            return "RPMSIGTAG_LONGSIZE";
        case RPMSIGTAG_LONGARCHIVESIZE:
            return "RPMSIGTAG_LONGARCHIVESIZE";
        case RPMSIGTAG_SHA256:
            return "RPMSIGTAG_SHA256";
        case RPMSIGTAG_FILESIGNATURES:
            return "RPMSIGTAG_FILESIGNATURES";
        case RPMSIGTAG_FILESIGNATURELENGTH:
            return "RPMSIGTAG_FILESIGNATURELENGTH";
        case RPMSIGTAG_VERITYSIGNATURES:
            return "RPMSIGTAG_VERITYSIGNATURES";
        case RPMSIGTAG_VERITYSIGNATUREALGO:
            return "RPMSIGTAG_VERITYSIGNATUREALGO";
        default:
            return "(unknown)";
    }
}

/*
 * Convert tag value to symbolic tag name (matches RPM headers).
 * Caller must not free string returned.
 */
const char *
tag_name(rpmTag tag)
{
    switch (tag) {
        case RPMTAG_HEADERIMAGE:
            return "RPMTAG_HEADERIMAGE";
        case RPMTAG_HEADERSIGNATURES:
            return "RPMTAG_HEADERSIGNATURES";
        case RPMTAG_HEADERIMMUTABLE:
            return "RPMTAG_HEADERIMMUTABLE";
        case RPMTAG_HEADERREGIONS:
            return "RPMTAG_HEADERREGIONS";
        case RPMTAG_HEADERI18NTABLE:
            return "RPMTAG_HEADERI18NTABLE";
        case RPMTAG_SIG_BASE:
            return "RPMTAG_SIG_BASE";
        case RPMTAG_SIGSIZE:
            return "RPMTAG_SIGSIZE";
        case RPMTAG_SIGLEMD5_1:
            return "RPMTAG_SIGLEMD5_1";
        case RPMTAG_SIGPGP:
            return "RPMTAG_SIGPGP";
        case RPMTAG_SIGLEMD5_2:
            return "RPMTAG_SIGLEMD5_2";
        case RPMTAG_SIGMD5:
            return "RPMTAG_SIGMD5";
        case RPMTAG_SIGGPG:
            return "RPMTAG_SIGGPG";
        case RPMTAG_SIGPGP5:
            return "RPMTAG_SIGPGP5";
        case RPMTAG_BADSHA1_1:
            return "RPMTAG_BADSHA1_1";
        case RPMTAG_BADSHA1_2:
            return "RPMTAG_BADSHA1_2";
        case RPMTAG_PUBKEYS:
            return "RPMTAG_PUBKEYS";
        case RPMTAG_DSAHEADER:
            return "RPMTAG_DSAHEADER";
        case RPMTAG_RSAHEADER:
            return "RPMTAG_RSAHEADER";
        case RPMTAG_SHA1HEADER:
            return "RPMTAG_SHA1HEADER";
        case RPMTAG_LONGSIGSIZE:
            return "RPMTAG_LONGSIGSIZE";
        case RPMTAG_LONGARCHIVESIZE:
            return "RPMTAG_LONGARCHIVESIZE";
        case RPMTAG_SHA256HEADER:
            return "RPMTAG_SHA256HEADER";
        case RPMTAG_VERITYSIGNATURES:
            return "RPMTAG_VERITYSIGNATURES";
        case RPMTAG_VERITYSIGNATUREALGO:
            return "RPMTAG_VERITYSIGNATUREALGO";
        case RPMTAG_NAME:
            return "RPMTAG_NAME";
        case RPMTAG_VERSION:
            return "RPMTAG_VERSION";
        case RPMTAG_RELEASE:
            return "RPMTAG_RELEASE";
        case RPMTAG_EPOCH:
            return "RPMTAG_EPOCH";
        case RPMTAG_SUMMARY:
            return "RPMTAG_SUMMARY";
        case RPMTAG_DESCRIPTION:
            return "RPMTAG_DESCRIPTION";
        case RPMTAG_BUILDTIME:
            return "RPMTAG_BUILDTIME";
        case RPMTAG_BUILDHOST:
            return "RPMTAG_BUILDHOST";
        case RPMTAG_INSTALLTIME:
            return "RPMTAG_INSTALLTIME";
        case RPMTAG_SIZE:
            return "RPMTAG_SIZE";
        case RPMTAG_DISTRIBUTION:
            return "RPMTAG_DISTRIBUTION";
        case RPMTAG_VENDOR:
            return "RPMTAG_VENDOR";
        case RPMTAG_GIF:
            return "RPMTAG_GIF";
        case RPMTAG_XPM:
            return "RPMTAG_XPM";
        case RPMTAG_LICENSE:
            return "RPMTAG_LICENSE";
        case RPMTAG_PACKAGER:
            return "RPMTAG_PACKAGER";
        case RPMTAG_GROUP:
            return "RPMTAG_GROUP";
        case RPMTAG_CHANGELOG:
            return "RPMTAG_CHANGELOG";
        case RPMTAG_SOURCE:
            return "RPMTAG_SOURCE";
        case RPMTAG_PATCH:
            return "RPMTAG_PATCH";
        case RPMTAG_URL:
            return "RPMTAG_URL";
        case RPMTAG_OS:
            return "RPMTAG_OS";
        case RPMTAG_ARCH:
            return "RPMTAG_ARCH";
        case RPMTAG_PREIN:
            return "RPMTAG_PREIN";
        case RPMTAG_POSTIN:
            return "RPMTAG_POSTIN";
        case RPMTAG_PREUN:
            return "RPMTAG_PREUN";
        case RPMTAG_POSTUN:
            return "RPMTAG_POSTUN";
        case RPMTAG_OLDFILENAMES:
            return "RPMTAG_OLDFILENAMES";
        case RPMTAG_FILESIZES:
            return "RPMTAG_FILESIZES";
        case RPMTAG_FILESTATES:
            return "RPMTAG_FILESTATES";
        case RPMTAG_FILEMODES:
            return "RPMTAG_FILEMODES";
        case RPMTAG_FILEUIDS:
            return "RPMTAG_FILEUIDS";
        case RPMTAG_FILEGIDS:
            return "RPMTAG_FILEGIDS";
        case RPMTAG_FILERDEVS:
            return "RPMTAG_FILERDEVS";
        case RPMTAG_FILEMTIMES:
            return "RPMTAG_FILEMTIMES";
        case RPMTAG_FILEDIGESTS:
            return "RPMTAG_FILEDIGESTS";
        case RPMTAG_FILELINKTOS:
            return "RPMTAG_FILELINKTOS";
        case RPMTAG_FILEFLAGS:
            return "RPMTAG_FILEFLAGS";
        case RPMTAG_ROOT:
            return "RPMTAG_ROOT";
        case RPMTAG_FILEUSERNAME:
            return "RPMTAG_FILEUSERNAME";
        case RPMTAG_FILEGROUPNAME:
            return "RPMTAG_FILEGROUPNAME";
        case RPMTAG_EXCLUDE:
            return "RPMTAG_EXCLUDE";
        case RPMTAG_EXCLUSIVE:
            return "RPMTAG_EXCLUSIVE";
        case RPMTAG_ICON:
            return "RPMTAG_ICON";
        case RPMTAG_SOURCERPM:
            return "RPMTAG_SOURCERPM";
        case RPMTAG_FILEVERIFYFLAGS:
            return "RPMTAG_FILEVERIFYFLAGS";
        case RPMTAG_ARCHIVESIZE:
            return "RPMTAG_ARCHIVESIZE";
        case RPMTAG_PROVIDENAME:
            return "RPMTAG_PROVIDENAME";
        case RPMTAG_REQUIREFLAGS:
            return "RPMTAG_REQUIREFLAGS";
        case RPMTAG_REQUIRENAME:
            return "RPMTAG_REQUIRENAME";
        case RPMTAG_REQUIREVERSION:
            return "RPMTAG_REQUIREVERSION";
        case RPMTAG_NOSOURCE:
            return "RPMTAG_NOSOURCE";
        case RPMTAG_NOPATCH:
            return "RPMTAG_NOPATCH";
        case RPMTAG_CONFLICTFLAGS:
            return "RPMTAG_CONFLICTFLAGS";
        case RPMTAG_CONFLICTNAME:
            return "RPMTAG_CONFLICTNAME";
        case RPMTAG_CONFLICTVERSION:
            return "RPMTAG_CONFLICTVERSION";
        case RPMTAG_DEFAULTPREFIX:
            return "RPMTAG_DEFAULTPREFIX";
        case RPMTAG_BUILDROOT:
            return "RPMTAG_BUILDROOT";
        case RPMTAG_INSTALLPREFIX:
            return "RPMTAG_INSTALLPREFIX";
        case RPMTAG_EXCLUDEARCH:
            return "RPMTAG_EXCLUDEARCH";
        case RPMTAG_EXCLUDEOS:
            return "RPMTAG_EXCLUDEOS";
        case RPMTAG_EXCLUSIVEARCH:
            return "RPMTAG_EXCLUSIVEARCH";
        case RPMTAG_EXCLUSIVEOS:
            return "RPMTAG_EXCLUSIVEOS";
        case RPMTAG_AUTOREQPROV:
            return "RPMTAG_AUTOREQPROV";
        case RPMTAG_RPMVERSION:
            return "RPMTAG_RPMVERSION";
        case RPMTAG_TRIGGERSCRIPTS:
            return "RPMTAG_TRIGGERSCRIPTS";
        case RPMTAG_TRIGGERNAME:
            return "RPMTAG_TRIGGERNAME";
        case RPMTAG_TRIGGERVERSION:
            return "RPMTAG_TRIGGERVERSION";
        case RPMTAG_TRIGGERFLAGS:
            return "RPMTAG_TRIGGERFLAGS";
        case RPMTAG_TRIGGERINDEX:
            return "RPMTAG_TRIGGERINDEX";
        case RPMTAG_VERIFYSCRIPT:
            return "RPMTAG_VERIFYSCRIPT";
        case RPMTAG_CHANGELOGTIME:
            return "RPMTAG_CHANGELOGTIME";
        case RPMTAG_CHANGELOGNAME:
            return "RPMTAG_CHANGELOGNAME";
        case RPMTAG_CHANGELOGTEXT:
            return "RPMTAG_CHANGELOGTEXT";
        case RPMTAG_BROKENMD5:
            return "RPMTAG_BROKENMD5";
        case RPMTAG_PREREQ:
            return "RPMTAG_PREREQ";
        case RPMTAG_PREINPROG:
            return "RPMTAG_PREINPROG";
        case RPMTAG_POSTINPROG:
            return "RPMTAG_POSTINPROG";
        case RPMTAG_PREUNPROG:
            return "RPMTAG_PREUNPROG";
        case RPMTAG_POSTUNPROG:
            return "RPMTAG_POSTUNPROG";
        case RPMTAG_BUILDARCHS:
            return "RPMTAG_BUILDARCHS";
        case RPMTAG_OBSOLETENAME:
            return "RPMTAG_OBSOLETENAME";
        case RPMTAG_VERIFYSCRIPTPROG:
            return "RPMTAG_VERIFYSCRIPTPROG";
        case RPMTAG_TRIGGERSCRIPTPROG:
            return "RPMTAG_TRIGGERSCRIPTPROG";
        case RPMTAG_DOCDIR:
            return "RPMTAG_DOCDIR";
        case RPMTAG_COOKIE:
            return "RPMTAG_COOKIE";
        case RPMTAG_FILEDEVICES:
            return "RPMTAG_FILEDEVICES";
        case RPMTAG_FILEINODES:
            return "RPMTAG_FILEINODES";
        case RPMTAG_FILELANGS:
            return "RPMTAG_FILELANGS";
        case RPMTAG_PREFIXES:
            return "RPMTAG_PREFIXES";
        case RPMTAG_INSTPREFIXES:
            return "RPMTAG_INSTPREFIXES";
        case RPMTAG_TRIGGERIN:
            return "RPMTAG_TRIGGERIN";
        case RPMTAG_TRIGGERUN:
            return "RPMTAG_TRIGGERUN";
        case RPMTAG_TRIGGERPOSTUN:
            return "RPMTAG_TRIGGERPOSTUN";
        case RPMTAG_AUTOREQ:
            return "RPMTAG_AUTOREQ";
        case RPMTAG_AUTOPROV:
            return "RPMTAG_AUTOPROV";
        case RPMTAG_CAPABILITY:
            return "RPMTAG_CAPABILITY";
        case RPMTAG_SOURCEPACKAGE:
            return "RPMTAG_SOURCEPACKAGE";
        case RPMTAG_OLDORIGFILENAMES:
            return "RPMTAG_OLDORIGFILENAMES";
        case RPMTAG_BUILDPREREQ:
            return "RPMTAG_BUILDPREREQ";
        case RPMTAG_BUILDREQUIRES:
            return "RPMTAG_BUILDREQUIRES";
        case RPMTAG_BUILDCONFLICTS:
            return "RPMTAG_BUILDCONFLICTS";
        case RPMTAG_BUILDMACROS:
            return "RPMTAG_BUILDMACROS";
        case RPMTAG_PROVIDEFLAGS:
            return "RPMTAG_PROVIDEFLAGS";
        case RPMTAG_PROVIDEVERSION:
            return "RPMTAG_PROVIDEVERSION";
        case RPMTAG_OBSOLETEFLAGS:
            return "RPMTAG_OBSOLETEFLAGS";
        case RPMTAG_OBSOLETEVERSION:
            return "RPMTAG_OBSOLETEVERSION";
        case RPMTAG_DIRINDEXES:
            return "RPMTAG_DIRINDEXES";
        case RPMTAG_BASENAMES:
            return "RPMTAG_BASENAMES";
        case RPMTAG_DIRNAMES:
            return "RPMTAG_DIRNAMES";
        case RPMTAG_ORIGDIRINDEXES:
            return "RPMTAG_ORIGDIRINDEXES";
        case RPMTAG_ORIGBASENAMES:
            return "RPMTAG_ORIGBASENAMES";
        case RPMTAG_ORIGDIRNAMES:
            return "RPMTAG_ORIGDIRNAMES";
        case RPMTAG_OPTFLAGS:
            return "RPMTAG_OPTFLAGS";
        case RPMTAG_DISTURL:
            return "RPMTAG_DISTURL";
        case RPMTAG_PAYLOADFORMAT:
            return "RPMTAG_PAYLOADFORMAT";
        case RPMTAG_PAYLOADCOMPRESSOR:
            return "RPMTAG_PAYLOADCOMPRESSOR";
        case RPMTAG_PAYLOADFLAGS:
            return "RPMTAG_PAYLOADFLAGS";
        case RPMTAG_INSTALLCOLOR:
            return "RPMTAG_INSTALLCOLOR";
        case RPMTAG_INSTALLTID:
            return "RPMTAG_INSTALLTID";
        case RPMTAG_REMOVETID:
            return "RPMTAG_REMOVETID";
        case RPMTAG_SHA1RHN:
            return "RPMTAG_SHA1RHN";
        case RPMTAG_RHNPLATFORM:
            return "RPMTAG_RHNPLATFORM";
        case RPMTAG_PLATFORM:
            return "RPMTAG_PLATFORM";
        case RPMTAG_PATCHESNAME:
            return "RPMTAG_PATCHESNAME";
        case RPMTAG_PATCHESFLAGS:
            return "RPMTAG_PATCHESFLAGS";
        case RPMTAG_PATCHESVERSION:
            return "RPMTAG_PATCHESVERSION";
        case RPMTAG_CACHECTIME:
            return "RPMTAG_CACHECTIME";
        case RPMTAG_CACHEPKGPATH:
            return "RPMTAG_CACHEPKGPATH";
        case RPMTAG_CACHEPKGSIZE:
            return "RPMTAG_CACHEPKGSIZE";
        case RPMTAG_CACHEPKGMTIME:
            return "RPMTAG_CACHEPKGMTIME";
        case RPMTAG_FILECOLORS:
            return "RPMTAG_FILECOLORS";
        case RPMTAG_FILECLASS:
            return "RPMTAG_FILECLASS";
        case RPMTAG_CLASSDICT:
            return "RPMTAG_CLASSDICT";
        case RPMTAG_FILEDEPENDSX:
            return "RPMTAG_FILEDEPENDSX";
        case RPMTAG_FILEDEPENDSN:
            return "RPMTAG_FILEDEPENDSN";
        case RPMTAG_DEPENDSDICT:
            return "RPMTAG_DEPENDSDICT";
        case RPMTAG_SOURCEPKGID:
            return "RPMTAG_SOURCEPKGID";
        case RPMTAG_FILECONTEXTS:
            return "RPMTAG_FILECONTEXTS";
        case RPMTAG_FSCONTEXTS:
            return "RPMTAG_FSCONTEXTS";
        case RPMTAG_RECONTEXTS:
            return "RPMTAG_RECONTEXTS";
        case RPMTAG_POLICIES:
            return "RPMTAG_POLICIES";
        case RPMTAG_PRETRANS:
            return "RPMTAG_PRETRANS";
        case RPMTAG_POSTTRANS:
            return "RPMTAG_POSTTRANS";
        case RPMTAG_PRETRANSPROG:
            return "RPMTAG_PRETRANSPROG";
        case RPMTAG_POSTTRANSPROG:
            return "RPMTAG_POSTTRANSPROG";
        case RPMTAG_DISTTAG:
            return "RPMTAG_DISTTAG";
        case RPMTAG_OLDSUGGESTSNAME:
            return "RPMTAG_OLDSUGGESTSNAME";
        case RPMTAG_OLDSUGGESTSVERSION:
            return "RPMTAG_OLDSUGGESTSVERSION";
        case RPMTAG_OLDSUGGESTSFLAGS:
            return "RPMTAG_OLDSUGGESTSFLAGS";
        case RPMTAG_OLDENHANCESNAME:
            return "RPMTAG_OLDENHANCESNAME";
        case RPMTAG_OLDENHANCESVERSION:
            return "RPMTAG_OLDENHANCESVERSION";
        case RPMTAG_OLDENHANCESFLAGS:
            return "RPMTAG_OLDENHANCESFLAGS";
        case RPMTAG_PRIORITY:
            return "RPMTAG_PRIORITY";
        case RPMTAG_CVSID:
            return "RPMTAG_CVSID";
        case RPMTAG_BLINKPKGID:
            return "RPMTAG_BLINKPKGID";
        case RPMTAG_BLINKHDRID:
            return "RPMTAG_BLINKHDRID";
        case RPMTAG_BLINKNEVRA:
            return "RPMTAG_BLINKNEVRA";
        case RPMTAG_FLINKPKGID:
            return "RPMTAG_FLINKPKGID";
        case RPMTAG_FLINKHDRID:
            return "RPMTAG_FLINKHDRID";
        case RPMTAG_FLINKNEVRA:
            return "RPMTAG_FLINKNEVRA";
        case RPMTAG_PACKAGEORIGIN:
            return "RPMTAG_PACKAGEORIGIN";
        case RPMTAG_TRIGGERPREIN:
            return "RPMTAG_TRIGGERPREIN";
        case RPMTAG_BUILDSUGGESTS:
            return "RPMTAG_BUILDSUGGESTS";
        case RPMTAG_BUILDENHANCES:
            return "RPMTAG_BUILDENHANCES";
        case RPMTAG_SCRIPTSTATES:
            return "RPMTAG_SCRIPTSTATES";
        case RPMTAG_SCRIPTMETRICS:
            return "RPMTAG_SCRIPTMETRICS";
        case RPMTAG_BUILDCPUCLOCK:
            return "RPMTAG_BUILDCPUCLOCK";
        case RPMTAG_FILEDIGESTALGOS:
            return "RPMTAG_FILEDIGESTALGOS";
        case RPMTAG_VARIANTS:
            return "RPMTAG_VARIANTS";
        case RPMTAG_XMAJOR:
            return "RPMTAG_XMAJOR";
        case RPMTAG_XMINOR:
            return "RPMTAG_XMINOR";
        case RPMTAG_REPOTAG:
            return "RPMTAG_REPOTAG";
        case RPMTAG_KEYWORDS:
            return "RPMTAG_KEYWORDS";
        case RPMTAG_BUILDPLATFORMS:
            return "RPMTAG_BUILDPLATFORMS";
        case RPMTAG_PACKAGECOLOR:
            return "RPMTAG_PACKAGECOLOR";
        case RPMTAG_PACKAGEPREFCOLOR:
            return "RPMTAG_PACKAGEPREFCOLOR";
        case RPMTAG_XATTRSDICT:
            return "RPMTAG_XATTRSDICT";
        case RPMTAG_FILEXATTRSX:
            return "RPMTAG_FILEXATTRSX";
        case RPMTAG_DEPATTRSDICT:
            return "RPMTAG_DEPATTRSDICT";
        case RPMTAG_CONFLICTATTRSX:
            return "RPMTAG_CONFLICTATTRSX";
        case RPMTAG_OBSOLETEATTRSX:
            return "RPMTAG_OBSOLETEATTRSX";
        case RPMTAG_PROVIDEATTRSX:
            return "RPMTAG_PROVIDEATTRSX";
        case RPMTAG_REQUIREATTRSX:
            return "RPMTAG_REQUIREATTRSX";
        case RPMTAG_BUILDPROVIDES:
            return "RPMTAG_BUILDPROVIDES";
        case RPMTAG_BUILDOBSOLETES:
            return "RPMTAG_BUILDOBSOLETES";
        case RPMTAG_DBINSTANCE:
            return "RPMTAG_DBINSTANCE";
        case RPMTAG_NVRA:
            return "RPMTAG_NVRA";
        case RPMTAG_FILENAMES:
            return "RPMTAG_FILENAMES";
        case RPMTAG_FILEPROVIDE:
            return "RPMTAG_FILEPROVIDE";
        case RPMTAG_FILEREQUIRE:
            return "RPMTAG_FILEREQUIRE";
        case RPMTAG_FSNAMES:
            return "RPMTAG_FSNAMES";
        case RPMTAG_FSSIZES:
            return "RPMTAG_FSSIZES";
        case RPMTAG_TRIGGERCONDS:
            return "RPMTAG_TRIGGERCONDS";
        case RPMTAG_TRIGGERTYPE:
            return "RPMTAG_TRIGGERTYPE";
        case RPMTAG_ORIGFILENAMES:
            return "RPMTAG_ORIGFILENAMES";
        case RPMTAG_LONGFILESIZES:
            return "RPMTAG_LONGFILESIZES";
        case RPMTAG_LONGSIZE:
            return "RPMTAG_LONGSIZE";
        case RPMTAG_FILECAPS:
            return "RPMTAG_FILECAPS";
        case RPMTAG_FILEDIGESTALGO:
            return "RPMTAG_FILEDIGESTALGO";
        case RPMTAG_BUGURL:
            return "RPMTAG_BUGURL";
        case RPMTAG_EVR:
            return "RPMTAG_EVR";
        case RPMTAG_NVR:
            return "RPMTAG_NVR";
        case RPMTAG_NEVR:
            return "RPMTAG_NEVR";
        case RPMTAG_NEVRA:
            return "RPMTAG_NEVRA";
        case RPMTAG_HEADERCOLOR:
            return "RPMTAG_HEADERCOLOR";
        case RPMTAG_VERBOSE:
            return "RPMTAG_VERBOSE";
        case RPMTAG_EPOCHNUM:
            return "RPMTAG_EPOCHNUM";
        case RPMTAG_PREINFLAGS:
            return "RPMTAG_PREINFLAGS";
        case RPMTAG_POSTINFLAGS:
            return "RPMTAG_POSTINFLAGS";
        case RPMTAG_PREUNFLAGS:
            return "RPMTAG_PREUNFLAGS";
        case RPMTAG_POSTUNFLAGS:
            return "RPMTAG_POSTUNFLAGS";
        case RPMTAG_PRETRANSFLAGS:
            return "RPMTAG_PRETRANSFLAGS";
        case RPMTAG_POSTTRANSFLAGS:
            return "RPMTAG_POSTTRANSFLAGS";
        case RPMTAG_VERIFYSCRIPTFLAGS:
            return "RPMTAG_VERIFYSCRIPTFLAGS";
        case RPMTAG_TRIGGERSCRIPTFLAGS:
            return "RPMTAG_TRIGGERSCRIPTFLAGS";
        case RPMTAG_COLLECTIONS:
            return "RPMTAG_COLLECTIONS";
        case RPMTAG_POLICYNAMES:
            return "RPMTAG_POLICYNAMES";
        case RPMTAG_POLICYTYPES:
            return "RPMTAG_POLICYTYPES";
        case RPMTAG_POLICYTYPESINDEXES:
            return "RPMTAG_POLICYTYPESINDEXES";
        case RPMTAG_POLICYFLAGS:
            return "RPMTAG_POLICYFLAGS";
        case RPMTAG_VCS:
            return "RPMTAG_VCS";
        case RPMTAG_ORDERNAME:
            return "RPMTAG_ORDERNAME";
        case RPMTAG_ORDERVERSION:
            return "RPMTAG_ORDERVERSION";
        case RPMTAG_ORDERFLAGS:
            return "RPMTAG_ORDERFLAGS";
        case RPMTAG_MSSFMANIFEST:
            return "RPMTAG_MSSFMANIFEST";
        case RPMTAG_MSSFDOMAIN:
            return "RPMTAG_MSSFDOMAIN";
        case RPMTAG_INSTFILENAMES:
            return "RPMTAG_INSTFILENAMES";
        case RPMTAG_REQUIRENEVRS:
            return "RPMTAG_REQUIRENEVRS";
        case RPMTAG_PROVIDENEVRS:
            return "RPMTAG_PROVIDENEVRS";
        case RPMTAG_OBSOLETENEVRS:
            return "RPMTAG_OBSOLETENEVRS";
        case RPMTAG_CONFLICTNEVRS:
            return "RPMTAG_CONFLICTNEVRS";
        case RPMTAG_FILENLINKS:
            return "RPMTAG_FILENLINKS";
        case RPMTAG_RECOMMENDNAME:
            return "RPMTAG_RECOMMENDNAME";
        case RPMTAG_RECOMMENDVERSION:
            return "RPMTAG_RECOMMENDVERSION";
        case RPMTAG_RECOMMENDFLAGS:
            return "RPMTAG_RECOMMENDFLAGS";
        case RPMTAG_SUGGESTNAME:
            return "RPMTAG_SUGGESTNAME";
        case RPMTAG_SUGGESTVERSION:
            return "RPMTAG_SUGGESTVERSION";
        case RPMTAG_SUGGESTFLAGS:
            return "RPMTAG_SUGGESTFLAGS";
        case RPMTAG_SUPPLEMENTNAME:
            return "RPMTAG_SUPPLEMENTNAME";
        case RPMTAG_SUPPLEMENTVERSION:
            return "RPMTAG_SUPPLEMENTVERSION";
        case RPMTAG_SUPPLEMENTFLAGS:
            return "RPMTAG_SUPPLEMENTFLAGS";
        case RPMTAG_ENHANCENAME:
            return "RPMTAG_ENHANCENAME";
        case RPMTAG_ENHANCEVERSION:
            return "RPMTAG_ENHANCEVERSION";
        case RPMTAG_ENHANCEFLAGS:
            return "RPMTAG_ENHANCEFLAGS";
        case RPMTAG_RECOMMENDNEVRS:
            return "RPMTAG_RECOMMENDNEVRS";
        case RPMTAG_SUGGESTNEVRS:
            return "RPMTAG_SUGGESTNEVRS";
        case RPMTAG_SUPPLEMENTNEVRS:
            return "RPMTAG_SUPPLEMENTNEVRS";
        case RPMTAG_ENHANCENEVRS:
            return "RPMTAG_ENHANCENEVRS";
        case RPMTAG_ENCODING:
            return "RPMTAG_ENCODING";
        case RPMTAG_FILETRIGGERIN:
            return "RPMTAG_FILETRIGGERIN";
        case RPMTAG_FILETRIGGERUN:
            return "RPMTAG_FILETRIGGERUN";
        case RPMTAG_FILETRIGGERPOSTUN:
            return "RPMTAG_FILETRIGGERPOSTUN";
        case RPMTAG_FILETRIGGERSCRIPTS:
            return "RPMTAG_FILETRIGGERSCRIPTS";
        case RPMTAG_FILETRIGGERSCRIPTPROG:
            return "RPMTAG_FILETRIGGERSCRIPTPROG";
        case RPMTAG_FILETRIGGERSCRIPTFLAGS:
            return "RPMTAG_FILETRIGGERSCRIPTFLAGS";
        case RPMTAG_FILETRIGGERNAME:
            return "RPMTAG_FILETRIGGERNAME";
        case RPMTAG_FILETRIGGERINDEX:
            return "RPMTAG_FILETRIGGERINDEX";
        case RPMTAG_FILETRIGGERVERSION:
            return "RPMTAG_FILETRIGGERVERSION";
        case RPMTAG_FILETRIGGERFLAGS:
            return "RPMTAG_FILETRIGGERFLAGS";
        case RPMTAG_TRANSFILETRIGGERIN:
            return "RPMTAG_TRANSFILETRIGGERIN";
        case RPMTAG_TRANSFILETRIGGERUN:
            return "RPMTAG_TRANSFILETRIGGERUN";
        case RPMTAG_TRANSFILETRIGGERPOSTUN:
            return "RPMTAG_TRANSFILETRIGGERPOSTUN";
        case RPMTAG_TRANSFILETRIGGERSCRIPTS:
            return "RPMTAG_TRANSFILETRIGGERSCRIPTS";
        case RPMTAG_TRANSFILETRIGGERSCRIPTPROG:
            return "RPMTAG_TRANSFILETRIGGERSCRIPTPROG";
        case RPMTAG_TRANSFILETRIGGERSCRIPTFLAGS:
            return "RPMTAG_TRANSFILETRIGGERSCRIPTFLAGS";
        case RPMTAG_TRANSFILETRIGGERNAME:
            return "RPMTAG_TRANSFILETRIGGERNAME";
        case RPMTAG_TRANSFILETRIGGERINDEX:
            return "RPMTAG_TRANSFILETRIGGERINDEX";
        case RPMTAG_TRANSFILETRIGGERVERSION:
            return "RPMTAG_TRANSFILETRIGGERVERSION";
        case RPMTAG_TRANSFILETRIGGERFLAGS:
            return "RPMTAG_TRANSFILETRIGGERFLAGS";
        case RPMTAG_REMOVEPATHPOSTFIXES:
            return "RPMTAG_REMOVEPATHPOSTFIXES";
        case RPMTAG_FILETRIGGERPRIORITIES:
            return "RPMTAG_FILETRIGGERPRIORITIES";
        case RPMTAG_TRANSFILETRIGGERPRIORITIES:
            return "RPMTAG_TRANSFILETRIGGERPRIORITIES";
        case RPMTAG_FILETRIGGERCONDS:
            return "RPMTAG_FILETRIGGERCONDS";
        case RPMTAG_FILETRIGGERTYPE:
            return "RPMTAG_FILETRIGGERTYPE";
        case RPMTAG_TRANSFILETRIGGERCONDS:
            return "RPMTAG_TRANSFILETRIGGERCONDS";
        case RPMTAG_TRANSFILETRIGGERTYPE:
            return "RPMTAG_TRANSFILETRIGGERTYPE";
        case RPMTAG_FILESIGNATURES:
            return "RPMTAG_FILESIGNATURES";
        case RPMTAG_FILESIGNATURELENGTH:
            return "RPMTAG_FILESIGNATURELENGTH";
        case RPMTAG_PAYLOADDIGEST:
            return "RPMTAG_PAYLOADDIGEST";
        case RPMTAG_PAYLOADDIGESTALGO:
            return "RPMTAG_PAYLOADDIGESTALGO";
        case RPMTAG_AUTOINSTALLED:
            return "RPMTAG_AUTOINSTALLED";
        case RPMTAG_IDENTITY:
            return "RPMTAG_IDENTITY";
        case RPMTAG_MODULARITYLABEL:
            return "RPMTAG_MODULARITYLABEL";
        case RPMTAG_PAYLOADDIGESTALT:
            return "RPMTAG_PAYLOADDIGESTALT";
        case RPMTAG_ARCHSUFFIX:
            return "RPMTAG_ARCHSUFFIX";
        case RPMTAG_SPEC:
            return "RPMTAG_SPEC";
        case RPMTAG_TRANSLATIONURL:
            return "RPMTAG_TRANSLATIONURL";
        case RPMTAG_UPSTREAMRELEASES:
            return "RPMTAG_UPSTREAMRELEASES";
        case RPMTAG_SOURCELICENSE:
            return "RPMTAG_SOURCELICENSE";
        case RPMTAG_PREUNTRANS:
            return "RPMTAG_PREUNTRANS";
        case RPMTAG_POSTUNTRANS:
            return "RPMTAG_POSTUNTRANS";
        case RPMTAG_PREUNTRANSPROG:
            return "RPMTAG_PREUNTRANSPROG";
        case RPMTAG_POSTUNTRANSPROG:
            return "RPMTAG_POSTUNTRANSPROG";
        case RPMTAG_PREUNTRANSFLAGS:
            return "RPMTAG_PREUNTRANSFLAGS";
        case RPMTAG_POSTUNTRANSFLAGS:
            return "RPMTAG_POSTUNTRANSFLAGS";
        case RPMTAG_SYSUSERS:
            return "RPMTAG_SYSUSERS";
        case RPMTAG_BUILDSYSTEM:
            return "RPMTAG_BUILDSYSTEM";
        case RPMTAG_BUILDOPTION:
            return "RPMTAG_BUILDOPTION";
        case RPMTAG_FIRSTFREE_TAG:
            return "RPMTAG_FIRSTFREE_TAG";
        default:
            return "(unknown)";
    }
}
