/*
 * Copyright The tarpm Project Authors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <CUnit/Basic.h>
#include <rpm/rpmtag.h>
#include "tarpm.h"

#include "test-main.h"

int
init_test_tags(void)
{
    return 0;
}

int
clean_test_tags(void)
{
    return 0;
}

void
test_strtagtype(void)
{
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_NULL_TYPE), "(null)") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_CHAR_TYPE), "char") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_INT8_TYPE), "int8") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_INT16_TYPE), "int16") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_INT32_TYPE), "int32") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_INT64_TYPE), "int64") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_STRING_TYPE), "string") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_BIN_TYPE), "binary blob") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_STRING_ARRAY_TYPE), "string array") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(RPM_I18NSTRING_TYPE), "i18n string") == 0);
    TARPM_ASSERT_TRUE(strcmp(strtagtype(47), "(unknown)") == 0);

    return;
}

void
test_signature_tag_name(void)
{
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_SIZE), "RPMSIGTAG_SIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_LEMD5_1), "RPMSIGTAG_LEMD5_1") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_PGP), "RPMSIGTAG_PGP") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_LEMD5_2), "RPMSIGTAG_LEMD5_2") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_MD5), "RPMSIGTAG_MD5") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_GPG), "RPMSIGTAG_GPG") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_PGP5), "RPMSIGTAG_PGP5") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_PAYLOADSIZE), "RPMSIGTAG_PAYLOADSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_RESERVEDSPACE), "RPMSIGTAG_RESERVEDSPACE") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_BADSHA1_1), "RPMSIGTAG_BADSHA1_1") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_BADSHA1_2), "RPMSIGTAG_BADSHA1_2") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_DSA), "RPMSIGTAG_DSA") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_RSA), "RPMSIGTAG_RSA") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_SHA1), "RPMSIGTAG_SHA1") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_LONGSIZE), "RPMSIGTAG_LONGSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_LONGARCHIVESIZE), "RPMSIGTAG_LONGARCHIVESIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_SHA256), "RPMSIGTAG_SHA256") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_FILESIGNATURES), "RPMSIGTAG_FILESIGNATURES") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_FILESIGNATURELENGTH), "RPMSIGTAG_FILESIGNATURELENGTH") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_VERITYSIGNATURES), "RPMSIGTAG_VERITYSIGNATURES") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(RPMSIGTAG_VERITYSIGNATUREALGO), "RPMSIGTAG_VERITYSIGNATUREALGO") == 0);
    TARPM_ASSERT_TRUE(strcmp(signature_tag_name(0), "(unknown)") == 0);

    return;
}

void
test_tag_name(void)
{
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERIMAGE), "RPMTAG_HEADERIMAGE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERSIGNATURES), "RPMTAG_HEADERSIGNATURES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERIMMUTABLE), "RPMTAG_HEADERIMMUTABLE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERREGIONS), "RPMTAG_HEADERREGIONS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERI18NTABLE), "RPMTAG_HEADERI18NTABLE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIG_BASE), "RPMTAG_SIG_BASE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGSIZE), "RPMTAG_SIGSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGLEMD5_1), "RPMTAG_SIGLEMD5_1") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGPGP), "RPMTAG_SIGPGP") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGLEMD5_2), "RPMTAG_SIGLEMD5_2") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGMD5), "RPMTAG_SIGMD5") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGGPG), "RPMTAG_SIGGPG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIGPGP5), "RPMTAG_SIGPGP5") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BADSHA1_1), "RPMTAG_BADSHA1_1") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BADSHA1_2), "RPMTAG_BADSHA1_2") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PUBKEYS), "RPMTAG_PUBKEYS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DSAHEADER), "RPMTAG_DSAHEADER") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RSAHEADER), "RPMTAG_RSAHEADER") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SHA1HEADER), "RPMTAG_SHA1HEADER") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_LONGSIGSIZE), "RPMTAG_LONGSIGSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_LONGARCHIVESIZE), "RPMTAG_LONGARCHIVESIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SHA256HEADER), "RPMTAG_SHA256HEADER") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERITYSIGNATURES), "RPMTAG_VERITYSIGNATURES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERITYSIGNATUREALGO), "RPMTAG_VERITYSIGNATUREALGO") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NAME), "RPMTAG_NAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERSION), "RPMTAG_VERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RELEASE), "RPMTAG_RELEASE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EPOCH), "RPMTAG_EPOCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUMMARY), "RPMTAG_SUMMARY") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DESCRIPTION), "RPMTAG_DESCRIPTION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDTIME), "RPMTAG_BUILDTIME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDHOST), "RPMTAG_BUILDHOST") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTALLTIME), "RPMTAG_INSTALLTIME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SIZE), "RPMTAG_SIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DISTRIBUTION), "RPMTAG_DISTRIBUTION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VENDOR), "RPMTAG_VENDOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_GIF), "RPMTAG_GIF") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_XPM), "RPMTAG_XPM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_LICENSE), "RPMTAG_LICENSE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PACKAGER), "RPMTAG_PACKAGER") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_GROUP), "RPMTAG_GROUP") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CHANGELOG), "RPMTAG_CHANGELOG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SOURCE), "RPMTAG_SOURCE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PATCH), "RPMTAG_PATCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_URL), "RPMTAG_URL") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OS), "RPMTAG_OS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ARCH), "RPMTAG_ARCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREIN), "RPMTAG_PREIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTIN), "RPMTAG_POSTIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUN), "RPMTAG_PREUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUN), "RPMTAG_POSTUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDFILENAMES), "RPMTAG_OLDFILENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILESIZES), "RPMTAG_FILESIZES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILESTATES), "RPMTAG_FILESTATES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEMODES), "RPMTAG_FILEMODES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEUIDS), "RPMTAG_FILEUIDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEGIDS), "RPMTAG_FILEGIDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILERDEVS), "RPMTAG_FILERDEVS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEMTIMES), "RPMTAG_FILEMTIMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDIGESTS), "RPMTAG_FILEDIGESTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILELINKTOS), "RPMTAG_FILELINKTOS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEFLAGS), "RPMTAG_FILEFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ROOT), "RPMTAG_ROOT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEUSERNAME), "RPMTAG_FILEUSERNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEGROUPNAME), "RPMTAG_FILEGROUPNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUDE), "RPMTAG_EXCLUDE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUSIVE), "RPMTAG_EXCLUSIVE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ICON), "RPMTAG_ICON") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SOURCERPM), "RPMTAG_SOURCERPM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEVERIFYFLAGS), "RPMTAG_FILEVERIFYFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ARCHIVESIZE), "RPMTAG_ARCHIVESIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PROVIDENAME), "RPMTAG_PROVIDENAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REQUIREFLAGS), "RPMTAG_REQUIREFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REQUIRENAME), "RPMTAG_REQUIRENAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REQUIREVERSION), "RPMTAG_REQUIREVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NOSOURCE), "RPMTAG_NOSOURCE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NOPATCH), "RPMTAG_NOPATCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CONFLICTFLAGS), "RPMTAG_CONFLICTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CONFLICTNAME), "RPMTAG_CONFLICTNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CONFLICTVERSION), "RPMTAG_CONFLICTVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DEFAULTPREFIX), "RPMTAG_DEFAULTPREFIX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDROOT), "RPMTAG_BUILDROOT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTALLPREFIX), "RPMTAG_INSTALLPREFIX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUDEARCH), "RPMTAG_EXCLUDEARCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUDEOS), "RPMTAG_EXCLUDEOS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUSIVEARCH), "RPMTAG_EXCLUSIVEARCH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EXCLUSIVEOS), "RPMTAG_EXCLUSIVEOS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_AUTOREQPROV), "RPMTAG_AUTOREQPROV") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RPMVERSION), "RPMTAG_RPMVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERSCRIPTS), "RPMTAG_TRIGGERSCRIPTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERNAME), "RPMTAG_TRIGGERNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERVERSION), "RPMTAG_TRIGGERVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERFLAGS), "RPMTAG_TRIGGERFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERINDEX), "RPMTAG_TRIGGERINDEX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERIFYSCRIPT), "RPMTAG_VERIFYSCRIPT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CHANGELOGTIME), "RPMTAG_CHANGELOGTIME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CHANGELOGNAME), "RPMTAG_CHANGELOGNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CHANGELOGTEXT), "RPMTAG_CHANGELOGTEXT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BROKENMD5), "RPMTAG_BROKENMD5") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREREQ), "RPMTAG_PREREQ") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREINPROG), "RPMTAG_PREINPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTINPROG), "RPMTAG_POSTINPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUNPROG), "RPMTAG_PREUNPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUNPROG), "RPMTAG_POSTUNPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDARCHS), "RPMTAG_BUILDARCHS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OBSOLETENAME), "RPMTAG_OBSOLETENAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERIFYSCRIPTPROG), "RPMTAG_VERIFYSCRIPTPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERSCRIPTPROG), "RPMTAG_TRIGGERSCRIPTPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DOCDIR), "RPMTAG_DOCDIR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_COOKIE), "RPMTAG_COOKIE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDEVICES), "RPMTAG_FILEDEVICES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEINODES), "RPMTAG_FILEINODES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILELANGS), "RPMTAG_FILELANGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREFIXES), "RPMTAG_PREFIXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTPREFIXES), "RPMTAG_INSTPREFIXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERIN), "RPMTAG_TRIGGERIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERUN), "RPMTAG_TRIGGERUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERPOSTUN), "RPMTAG_TRIGGERPOSTUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_AUTOREQ), "RPMTAG_AUTOREQ") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_AUTOPROV), "RPMTAG_AUTOPROV") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CAPABILITY), "RPMTAG_CAPABILITY") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SOURCEPACKAGE), "RPMTAG_SOURCEPACKAGE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDORIGFILENAMES), "RPMTAG_OLDORIGFILENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDPREREQ), "RPMTAG_BUILDPREREQ") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDREQUIRES), "RPMTAG_BUILDREQUIRES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDCONFLICTS), "RPMTAG_BUILDCONFLICTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDMACROS), "RPMTAG_BUILDMACROS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PROVIDEFLAGS), "RPMTAG_PROVIDEFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PROVIDEVERSION), "RPMTAG_PROVIDEVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OBSOLETEFLAGS), "RPMTAG_OBSOLETEFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OBSOLETEVERSION), "RPMTAG_OBSOLETEVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DIRINDEXES), "RPMTAG_DIRINDEXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BASENAMES), "RPMTAG_BASENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DIRNAMES), "RPMTAG_DIRNAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORIGDIRINDEXES), "RPMTAG_ORIGDIRINDEXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORIGBASENAMES), "RPMTAG_ORIGBASENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORIGDIRNAMES), "RPMTAG_ORIGDIRNAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OPTFLAGS), "RPMTAG_OPTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DISTURL), "RPMTAG_DISTURL") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADFORMAT), "RPMTAG_PAYLOADFORMAT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADCOMPRESSOR), "RPMTAG_PAYLOADCOMPRESSOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADFLAGS), "RPMTAG_PAYLOADFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTALLCOLOR), "RPMTAG_INSTALLCOLOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTALLTID), "RPMTAG_INSTALLTID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REMOVETID), "RPMTAG_REMOVETID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SHA1RHN), "RPMTAG_SHA1RHN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RHNPLATFORM), "RPMTAG_RHNPLATFORM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PLATFORM), "RPMTAG_PLATFORM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PATCHESNAME), "RPMTAG_PATCHESNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PATCHESFLAGS), "RPMTAG_PATCHESFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PATCHESVERSION), "RPMTAG_PATCHESVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CACHECTIME), "RPMTAG_CACHECTIME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CACHEPKGPATH), "RPMTAG_CACHEPKGPATH") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CACHEPKGSIZE), "RPMTAG_CACHEPKGSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CACHEPKGMTIME), "RPMTAG_CACHEPKGMTIME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILECOLORS), "RPMTAG_FILECOLORS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILECLASS), "RPMTAG_FILECLASS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CLASSDICT), "RPMTAG_CLASSDICT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDEPENDSX), "RPMTAG_FILEDEPENDSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDEPENDSN), "RPMTAG_FILEDEPENDSN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DEPENDSDICT), "RPMTAG_DEPENDSDICT") == 0);
#ifdef RPMTAG_SOURCEPKGID
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SOURCEPKGID), "RPMTAG_SOURCEPKGID") == 0);
#endif
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILECONTEXTS), "RPMTAG_FILECONTEXTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FSCONTEXTS), "RPMTAG_FSCONTEXTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RECONTEXTS), "RPMTAG_RECONTEXTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POLICIES), "RPMTAG_POLICIES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PRETRANS), "RPMTAG_PRETRANS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTTRANS), "RPMTAG_POSTTRANS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PRETRANSPROG), "RPMTAG_PRETRANSPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTTRANSPROG), "RPMTAG_POSTTRANSPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DISTTAG), "RPMTAG_DISTTAG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDSUGGESTSNAME), "RPMTAG_OLDSUGGESTSNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDSUGGESTSVERSION), "RPMTAG_OLDSUGGESTSVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDSUGGESTSFLAGS), "RPMTAG_OLDSUGGESTSFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDENHANCESNAME), "RPMTAG_OLDENHANCESNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDENHANCESVERSION), "RPMTAG_OLDENHANCESVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OLDENHANCESFLAGS), "RPMTAG_OLDENHANCESFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PRIORITY), "RPMTAG_PRIORITY") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CVSID), "RPMTAG_CVSID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BLINKPKGID), "RPMTAG_BLINKPKGID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BLINKHDRID), "RPMTAG_BLINKHDRID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BLINKNEVRA), "RPMTAG_BLINKNEVRA") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FLINKPKGID), "RPMTAG_FLINKPKGID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FLINKHDRID), "RPMTAG_FLINKHDRID") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FLINKNEVRA), "RPMTAG_FLINKNEVRA") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PACKAGEORIGIN), "RPMTAG_PACKAGEORIGIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERPREIN), "RPMTAG_TRIGGERPREIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDSUGGESTS), "RPMTAG_BUILDSUGGESTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDENHANCES), "RPMTAG_BUILDENHANCES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SCRIPTSTATES), "RPMTAG_SCRIPTSTATES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SCRIPTMETRICS), "RPMTAG_SCRIPTMETRICS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDCPUCLOCK), "RPMTAG_BUILDCPUCLOCK") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDIGESTALGOS), "RPMTAG_FILEDIGESTALGOS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VARIANTS), "RPMTAG_VARIANTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_XMAJOR), "RPMTAG_XMAJOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_XMINOR), "RPMTAG_XMINOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REPOTAG), "RPMTAG_REPOTAG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_KEYWORDS), "RPMTAG_KEYWORDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDPLATFORMS), "RPMTAG_BUILDPLATFORMS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PACKAGECOLOR), "RPMTAG_PACKAGECOLOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PACKAGEPREFCOLOR), "RPMTAG_PACKAGEPREFCOLOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_XATTRSDICT), "RPMTAG_XATTRSDICT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEXATTRSX), "RPMTAG_FILEXATTRSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DEPATTRSDICT), "RPMTAG_DEPATTRSDICT") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CONFLICTATTRSX), "RPMTAG_CONFLICTATTRSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OBSOLETEATTRSX), "RPMTAG_OBSOLETEATTRSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PROVIDEATTRSX), "RPMTAG_PROVIDEATTRSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REQUIREATTRSX), "RPMTAG_REQUIREATTRSX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDPROVIDES), "RPMTAG_BUILDPROVIDES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDOBSOLETES), "RPMTAG_BUILDOBSOLETES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_DBINSTANCE), "RPMTAG_DBINSTANCE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NVRA), "RPMTAG_NVRA") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILENAMES), "RPMTAG_FILENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEPROVIDE), "RPMTAG_FILEPROVIDE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEREQUIRE), "RPMTAG_FILEREQUIRE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FSNAMES), "RPMTAG_FSNAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FSSIZES), "RPMTAG_FSSIZES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERCONDS), "RPMTAG_TRIGGERCONDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERTYPE), "RPMTAG_TRIGGERTYPE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORIGFILENAMES), "RPMTAG_ORIGFILENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_LONGFILESIZES), "RPMTAG_LONGFILESIZES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_LONGSIZE), "RPMTAG_LONGSIZE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILECAPS), "RPMTAG_FILECAPS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILEDIGESTALGO), "RPMTAG_FILEDIGESTALGO") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUGURL), "RPMTAG_BUGURL") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EVR), "RPMTAG_EVR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NVR), "RPMTAG_NVR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NEVR), "RPMTAG_NEVR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_NEVRA), "RPMTAG_NEVRA") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_HEADERCOLOR), "RPMTAG_HEADERCOLOR") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERBOSE), "RPMTAG_VERBOSE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_EPOCHNUM), "RPMTAG_EPOCHNUM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREINFLAGS), "RPMTAG_PREINFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTINFLAGS), "RPMTAG_POSTINFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUNFLAGS), "RPMTAG_PREUNFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUNFLAGS), "RPMTAG_POSTUNFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PRETRANSFLAGS), "RPMTAG_PRETRANSFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTTRANSFLAGS), "RPMTAG_POSTTRANSFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VERIFYSCRIPTFLAGS), "RPMTAG_VERIFYSCRIPTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRIGGERSCRIPTFLAGS), "RPMTAG_TRIGGERSCRIPTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_COLLECTIONS), "RPMTAG_COLLECTIONS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POLICYNAMES), "RPMTAG_POLICYNAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POLICYTYPES), "RPMTAG_POLICYTYPES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POLICYTYPESINDEXES), "RPMTAG_POLICYTYPESINDEXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POLICYFLAGS), "RPMTAG_POLICYFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_VCS), "RPMTAG_VCS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORDERNAME), "RPMTAG_ORDERNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORDERVERSION), "RPMTAG_ORDERVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ORDERFLAGS), "RPMTAG_ORDERFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_MSSFMANIFEST), "RPMTAG_MSSFMANIFEST") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_MSSFDOMAIN), "RPMTAG_MSSFDOMAIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_INSTFILENAMES), "RPMTAG_INSTFILENAMES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REQUIRENEVRS), "RPMTAG_REQUIRENEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PROVIDENEVRS), "RPMTAG_PROVIDENEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_OBSOLETENEVRS), "RPMTAG_OBSOLETENEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_CONFLICTNEVRS), "RPMTAG_CONFLICTNEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILENLINKS), "RPMTAG_FILENLINKS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RECOMMENDNAME), "RPMTAG_RECOMMENDNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RECOMMENDVERSION), "RPMTAG_RECOMMENDVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RECOMMENDFLAGS), "RPMTAG_RECOMMENDFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUGGESTNAME), "RPMTAG_SUGGESTNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUGGESTVERSION), "RPMTAG_SUGGESTVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUGGESTFLAGS), "RPMTAG_SUGGESTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUPPLEMENTNAME), "RPMTAG_SUPPLEMENTNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUPPLEMENTVERSION), "RPMTAG_SUPPLEMENTVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUPPLEMENTFLAGS), "RPMTAG_SUPPLEMENTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ENHANCENAME), "RPMTAG_ENHANCENAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ENHANCEVERSION), "RPMTAG_ENHANCEVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ENHANCEFLAGS), "RPMTAG_ENHANCEFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_RECOMMENDNEVRS), "RPMTAG_RECOMMENDNEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUGGESTNEVRS), "RPMTAG_SUGGESTNEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SUPPLEMENTNEVRS), "RPMTAG_SUPPLEMENTNEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ENHANCENEVRS), "RPMTAG_ENHANCENEVRS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ENCODING), "RPMTAG_ENCODING") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERIN), "RPMTAG_FILETRIGGERIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERUN), "RPMTAG_FILETRIGGERUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERPOSTUN), "RPMTAG_FILETRIGGERPOSTUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERSCRIPTS), "RPMTAG_FILETRIGGERSCRIPTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERSCRIPTPROG), "RPMTAG_FILETRIGGERSCRIPTPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERSCRIPTFLAGS), "RPMTAG_FILETRIGGERSCRIPTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERNAME), "RPMTAG_FILETRIGGERNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERINDEX), "RPMTAG_FILETRIGGERINDEX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERVERSION), "RPMTAG_FILETRIGGERVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERFLAGS), "RPMTAG_FILETRIGGERFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERIN), "RPMTAG_TRANSFILETRIGGERIN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERUN), "RPMTAG_TRANSFILETRIGGERUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERPOSTUN), "RPMTAG_TRANSFILETRIGGERPOSTUN") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERSCRIPTS), "RPMTAG_TRANSFILETRIGGERSCRIPTS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERSCRIPTPROG), "RPMTAG_TRANSFILETRIGGERSCRIPTPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERSCRIPTFLAGS), "RPMTAG_TRANSFILETRIGGERSCRIPTFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERNAME), "RPMTAG_TRANSFILETRIGGERNAME") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERINDEX), "RPMTAG_TRANSFILETRIGGERINDEX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERVERSION), "RPMTAG_TRANSFILETRIGGERVERSION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERFLAGS), "RPMTAG_TRANSFILETRIGGERFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_REMOVEPATHPOSTFIXES), "RPMTAG_REMOVEPATHPOSTFIXES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERPRIORITIES), "RPMTAG_FILETRIGGERPRIORITIES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERPRIORITIES), "RPMTAG_TRANSFILETRIGGERPRIORITIES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERCONDS), "RPMTAG_FILETRIGGERCONDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILETRIGGERTYPE), "RPMTAG_FILETRIGGERTYPE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERCONDS), "RPMTAG_TRANSFILETRIGGERCONDS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSFILETRIGGERTYPE), "RPMTAG_TRANSFILETRIGGERTYPE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILESIGNATURES), "RPMTAG_FILESIGNATURES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FILESIGNATURELENGTH), "RPMTAG_FILESIGNATURELENGTH") == 0);
#ifdef RPMTAG_PAYLOADDIGEST
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADDIGEST), "RPMTAG_PAYLOADDIGEST") == 0);
#endif
#ifdef RPMTAG_PAYLOADDIGESTALGO
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADDIGESTALGO), "RPMTAG_PAYLOADDIGESTALGO") == 0);
#endif
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_AUTOINSTALLED), "RPMTAG_AUTOINSTALLED") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_IDENTITY), "RPMTAG_IDENTITY") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_MODULARITYLABEL), "RPMTAG_MODULARITYLABEL") == 0);
#ifdef RPMTAG_PAYLOADDIGESTALT
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PAYLOADDIGESTALT), "RPMTAG_PAYLOADDIGESTALT") == 0);
#endif
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_ARCHSUFFIX), "RPMTAG_ARCHSUFFIX") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SPEC), "RPMTAG_SPEC") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_TRANSLATIONURL), "RPMTAG_TRANSLATIONURL") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_UPSTREAMRELEASES), "RPMTAG_UPSTREAMRELEASES") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SOURCELICENSE), "RPMTAG_SOURCELICENSE") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUNTRANS), "RPMTAG_PREUNTRANS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUNTRANS), "RPMTAG_POSTUNTRANS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUNTRANSPROG), "RPMTAG_PREUNTRANSPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUNTRANSPROG), "RPMTAG_POSTUNTRANSPROG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_PREUNTRANSFLAGS), "RPMTAG_PREUNTRANSFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_POSTUNTRANSFLAGS), "RPMTAG_POSTUNTRANSFLAGS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_SYSUSERS), "RPMTAG_SYSUSERS") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDSYSTEM), "RPMTAG_BUILDSYSTEM") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_BUILDOPTION), "RPMTAG_BUILDOPTION") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(RPMTAG_FIRSTFREE_TAG), "RPMTAG_FIRSTFREE_TAG") == 0);
    TARPM_ASSERT_TRUE(strcmp(tag_name(-1), "(unknown)") == 0);

    return;
}

CU_pSuite
get_suite(void)
{
    CU_pSuite pSuite = NULL;

    /* add a suite to the registry */
    pSuite = CU_add_suite("tags", init_test_tags, clean_test_tags);

    if (pSuite == NULL) {
        return NULL;
    }

    /* add tests to the suite */
    if (CU_add_test(pSuite, "test strtagtype()", test_strtagtype) == NULL ||
        CU_add_test(pSuite, "test signature_tag_name()", test_signature_tag_name) == NULL ||
        CU_add_test(pSuite, "test tag_name()", test_tag_name) == NULL) {
        return NULL;
    }

    return pSuite;
}
